### PR TITLE
added option to control connection re-use

### PR DESCRIPTION
**Pull request by ulisesflynn**

### CODE REVIEW

**Comment by mna** [comment]
Hello Ulises,

What issue does it fix? Or what new feature does it provide? There is no description, no comment and no test, it breaks the build (existing tests were not adjusted) and API compatibility, and the relationship with the linked Go issue is not clear to me (that go issue was fixed a long time ago, apparently). Why would you use that “reuse” parameter instead of the existing Transport.DisableKeepAlives?

Thanks,
Martin

**Comment by ulisesflynn** [comment]
Martin,

Thank you for quick comments, sorry for my slow response, I've been busy during the holiday.
I use rehttp's transport to set retries, then I send it to another library that makes the client call. This has been working great, but I frequently get EOF errors from the client call, which I think is happening due to keep alives being on. I do see that the base go transport package implements disablekeepalives by adding a header: https://golang.org/src/net/http/transport.go#L1934. Could this functionality be added to the rehttp's roundtrip?

Thank you,
Ulises.

**Comment by mna** [comment]
Hello,

You should set it on the http.Transport that you pass to rehttp.NewTransport. There's no need to add it to rehttp as it can and should be set on the nested (real) Transport.

Hope this helps,
Martin

**Comment by ulisesflynn** [comment]
Martin,

Thanks, that is exactly what I was looking for, didn't see that you can pass in a transport.

Thank you,
Ulises.

**Pull request closed without merging**
